name: Daily A-Share Check

on:
  schedule:
    - cron: '30 9 * * *' # 这里的 UTC 9:30 约等于北京时间下午 17:30
  workflow_dispatch: # 支持手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install akshare pandas requests
      - name: Run Script
        env:
          SC_KEY: ${{ secrets.SC_KEY }}
        run: python wechat_notify.py
